export const DummyData1 = {
      nodes: [
        { id: "Nav_1", fields: { label: "Nav_1", listDirection: "H", recursiveChildren: false, alwaysRender: false } },
        { id: "Nav_2", fields: { label: "Nav_2", listDirection: "H", recursiveChildren: false, alwaysRender: false } },
        { id: "Nav_3", fields: { label: "Nav_3", listDirection: "H", recursiveChildren: false, alwaysRender: true } },
        { id: "Nav_4", fields: { label: "Nav_4", listDirection: "H", recursiveChildren: false, alwaysRender: true } },
        { id: "Nav_5", fields: { label: "Nav_5", listDirection: "H", recursiveChildren: false, alwaysRender: true } },
        { id: "Nav_6", fields: { label: "Nav_6", listDirection: "H", recursiveChildren: false, alwaysRender: true } },
        { id: "Nav_7", fields: { label: "Nav_7", listDirection: "H", recursiveChildren: false, alwaysRender: true } },
        { id: "Nav_8", fields: { label: "Nav_8", listDirection: "H", recursiveChildren: false, alwaysRender: true } },
        { id: "Nav_9", fields: { label: "Nav_9", listDirection: "H", recursiveChildren: false, alwaysRender: true } },

        { id: "Kanban_1", fields: { label: "Kanban_1", listDirection: "V", recursiveChildren: false, alwaysRender: false } },
        { id: "Kanban_2", fields: { label: "Kanban_2", listDirection: "V", recursiveChildren: false, alwaysRender: false } },
        { id: "Kanban_3", fields: { label: "Kanban_3", listDirection: "V", recursiveChildren: false, alwaysRender: false } },
        { id: "Kanban_4", fields: { label: "Kanban_4", listDirection: "V", recursiveChildren: false, alwaysRender: false } },
        { id: "Kanban_5", fields: { label: "Kanban_5", listDirection: "V", recursiveChildren: false, alwaysRender: false } },

        { id: "Tender_1", fields: { label: "Tender_1", listDirection: "H", recursiveChildren: false, alwaysRender: true } },
        { id: "Tender_2", fields: { label: "Tender_2", listDirection: "H", recursiveChildren: false, alwaysRender: true } },
        { id: "Tender_3", fields: { label: "Tender_3", listDirection: "H", recursiveChildren: false, alwaysRender: true } },
        { id: "Tender_4", fields: { label: "Tender_4", listDirection: "H", recursiveChildren: false, alwaysRender: true } },
        { id: "Tender_5", fields: { label: "Tender_5", listDirection: "H", recursiveChildren: false, alwaysRender: true } },
        { id: "Tender_6", fields: { label: "Tender_6", listDirection: "H", recursiveChildren: false, alwaysRender: true } },
        { id: "Tender_7", fields: { label: "Tender_7", listDirection: "H", recursiveChildren: false, alwaysRender: true } },
        { id: "Tender_8", fields: { label: "Tender_8", listDirection: "H", recursiveChildren: false, alwaysRender: true } },
        { id: "Tender_9", fields: { label: "Tender_9", listDirection: "H", recursiveChildren: false, alwaysRender: true } },
        { id: "Tender_10", fields: { label: "Tender_10", listDirection: "H", recursiveChildren: false, alwaysRender: true } },
        { id: "Tender_11", fields: { label: "Tender_11", listDirection: "H", recursiveChildren: false, alwaysRender: true } },
        { id: "Tender_12", fields: { label: "Tender_12", listDirection: "H", recursiveChildren: false, alwaysRender: true } },
        // New children for Kanban_2
        { id: "Tender_13", fields: { label: "Tender_13", listDirection: "H", recursiveChildren: false, alwaysRender: true } },
        { id: "Tender_14", fields: { label: "Tender_14", listDirection: "H", recursiveChildren: false, alwaysRender: true } },
        // New children for Kanban_4
        { id: "Tender_15", fields: { label: "Tender_15", listDirection: "H", recursiveChildren: false, alwaysRender: true } },
        { id: "Tender_16", fields: { label: "Tender_16", listDirection: "H", recursiveChildren: false, alwaysRender: true } },
        { id: "Tender_17", fields: { label: "Tender_17", listDirection: "H", recursiveChildren: false, alwaysRender: true } },
        { id: "Tender_18", fields: { label: "Tender_18", listDirection: "H", recursiveChildren: false, alwaysRender: true } },

        { id: "Not started", fields: { label: "Not started", listDirection: "V", recursiveChildren: false, alwaysRender: false } },
        { id: "Authoring", fields: { label: "Authoring", listDirection: "V", recursiveChildren: false, alwaysRender: false } },
        { id: "Review", fields: { label: "Review", listDirection: "V", recursiveChildren: false, alwaysRender: false } },
        { id: "Submitted", fields: { label: "Submitted", listDirection: "V", recursiveChildren: false, alwaysRender: false } },
        { id: "Project ABC", fields: { label: "Project ABC", listDirection: "H", recursiveChildren: false, alwaysRender: true } },
        { id: "Project DEF", fields: { label: "Project DEF", listDirection: "H", recursiveChildren: false, alwaysRender: true } },
        { id: "Project GHI", fields: { label: "Project GHI", listDirection: "H", recursiveChildren: false, alwaysRender: true } },
        { id: "Project JKL", fields: { label: "Project JKL", listDirection: "H", recursiveChildren: false, alwaysRender: true } }
      ],
      edges: [
        { parent: "Nav_1", child: "Kanban_1" },
        { parent: "Nav_1", child: "Kanban_2" },
        { parent: "Nav_1", child: "Kanban_3" },
        { parent: "Nav_1", child: "Kanban_4" },
        { parent: "Nav_1", child: "Kanban_5" },
        { parent: "Kanban_1", child: "Tender_1" },
        { parent: "Kanban_1", child: "Tender_2" },
        { parent: "Kanban_1", child: "Tender_3" },
        { parent: "Kanban_1", child: "Tender_4" },
        { parent: "Kanban_1", child: "Tender_5" },
        { parent: "Kanban_1", child: "Tender_6" },
        { parent: "Kanban_1", child: "Tender_7" },
        { parent: "Kanban_1", child: "Tender_8" },
        { parent: "Kanban_1", child: "Tender_9" },
        { parent: "Kanban_1", child: "Tender_10" },
        { parent: "Kanban_1", child: "Tender_11" },
        { parent: "Kanban_1", child: "Tender_12" },
        { parent: "Kanban_2", child: "Tender_13" },
        { parent: "Kanban_2", child: "Tender_14" },
        { parent: "Kanban_4", child: "Tender_15" },
        { parent: "Kanban_4", child: "Tender_16" },
        { parent: "Kanban_4", child: "Tender_17" },
        { parent: "Kanban_4", child: "Tender_18" },
        { parent: "Nav_2", child: "Not started" },
        { parent: "Nav_2", child: "Authoring" },
        { parent: "Nav_2", child: "Review" },
        { parent: "Nav_2", child: "Submitted" },
        { parent: "Not started", child: "Project ABC" },
        { parent: "Authoring", child: "Project DEF" },
        { parent: "Authoring", child: "Project GHI" },
        { parent: "Authoring", child: "Project JKL" }
      ]
    };
